AB#8789 Add a "push:media" serialization script
Sitecore/Sitecore.Demo.CHONE pull request #147
Opened 2023-06-15 12:19 UTC by chpa7

2023-07-05 21:05 UTC, jflheureux requested changes

2023-07-05 21:05 UTC, jflheureux commented on serialization/items/media/-/-WRFFhlq0kOeQ_0xs4eZ_g/-WRFFhlq0kOeQ_0xs4eZ_g.media.yaml
> +description: Test publish error
Could this media item description be reverted?

2023-07-05 21:05 UTC, jflheureux commented on serialization/README.md
> +## Starting with an empty Content Hub ONE instance
Please move this section just after `## Connecting a Content Hub ONE instance to the CLI`.

Then, move the other sections as H3 under a H2 named `## Operations`

2023-08-28 10:51 UTC, sc-nelikostadinova approved these changes

2023-08-31 15:39 UTC, jflheureux approved these changes

2023-09-01 10:02 UTC, merged